####################
# Default Settings #
####################
settings:
  cache: true
  cache_expiration: 30
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 15
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  check_nightly: false
  run_order:
  - operations
  - metadata
  - overlays
  - collections
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 90
  show_unfiltered: false

##################
# Webhook Config #
##################
  default_collection_order:
  ignore_ids:
  ignore_imdb_ids:
  playlist_exclude_users:
  custom_repo:
webhooks:
  error:
  version:
  run_start:
  run_end:
  delete:

#############
# Plex Auth #
#############
plex:
  url: http://192.168.103.40:32400
  token: XXXXXXXXXXXXXXXXXXXXXXX
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

##############
# TMDB Auth  #
##############
  verify_ssl:
  db_cache:
tmdb:
  apikey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  language: en
  cache_expiration: 7

################
# MDBList Auth #
################
# 2026-03-26 - Not currently pulling any data / API Limit of 1000 hits per day.
  region:
mdblist:
  apikey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

####################
# Library Settings #
####################
  region:
  cache_expiration: 1440
libraries:

############
## Movies ##
############
  Movies:
    reapply_overlays: false                                  # Set to true when changing overlay; false for daily runs.
    remove_overlays: false                                  # Set to true to clear all overlays from this library.
    overlay_files:

    - pmm: resolution                                      # Resolution - Bottom Left
      template_variables:
        horizontal_align: left
        vertical_align: bottom
        back_align: left
        horizontal_offset: 0
        vertical_offset: 0
        back_width: "1100"
        back_height: 80
        back_color: '#000000'
        back_padding: 0
        back_radius: 0        
        resolution_font: /config/overlays/Fonts/AptosNarrowBold.ttf
        resolution_font_size: 60
        resolution_font_color: '#FFFFFF'

    - pmm: ratings                                          # Ratings - Bottom Center
      template_variables:
        rating1: audience
        rating1_image: rt_popcorn
        rating1_font: /config/overlays/Fonts/AptosNarrowBold.ttf
        rating1_font_size: 76
        rating1_font_color: '#FFFFFF'
        rating_alignment: horizontal
        back_width: "1100"
        back_height: 80
        back_color: '#00000000'
        back_padding: 0
        back_radius: 0 
        horizontal_position: center
        vertical_position: bottom
        rating1_horizontal_offset: 0
        rating1_vertical_offset: 0

    - default: studio                                       # Studio - Bottom Right
      template_variables:
        horizontal_align: right
        vertical_align: bottom
        back_align: right
        horizontal_offset: 0
        vertical_offset: 0
        back_color: '#000000'
        back_height: 70
        back_padding: 0
        studio_font_size: 50

    collection_files:
    - default: franchise                                    # Collections (by franchise)
      template_variables:
        collection_order: release
        build_collection: true

##############
## TV Shows ##
##############
  TV Shows:
    reapply_overlays: false                                  # Set to true when changing overlay; false for daily runs.
    remove_overlays: false                                  # Set to true to clear all overlays from this library.
    overlay_files:

    - pmm: status                                           # Show Status (Airing, Ended, etc) - Top Center
      template_variables:
        horizontal_align: center
        vertical_align: top
        vertical_offset: 0
        horizontal_offset: 0
        back_height: 60
        back_width: "1100"
        font: /config/overlays/Fonts/AptosNarrowBold.ttf
        font_size: 64
        back_color_airing: '#016920'                        # Green
        back_color_returning: '#000847'                     # Blue
        back_color_canceled: '#ed1f1f'                      # Red
        back_color_ended: '#ed1f1f'                         # Red

    - pmm: resolution                                      # Resolution - Bottom Left
      template_variables:
        horizontal_align: left
        vertical_align: bottom
        back_align: left
        horizontal_offset: 0
        vertical_offset: 0
        back_width: "1100"
        back_height: 80
        back_color: '#000000'
        back_padding: 0
        back_radius: 0        
        resolution_font: /config/overlays/Fonts/AptosNarrowBold.ttf
        resolution_font_size: 60
        resolution_font_color: '#FFFFFF'

    - pmm: ratings                                          # Ratings - Bottom Center
      template_variables:
        rating1: audience
        rating1_image: rt_popcorn
        rating1_font: /config/overlays/Fonts/AptosNarrowBold.ttf
        rating1_font_size: 76
        rating1_font_color: '#FFFFFF'
        rating_alignment: horizontal
        horizontal_position: center
        vertical_position: bottom
        horizontal_offset: 0
        vertical_offset: 0
        rating1_horizontal_offset: 0
        rating1_vertical_offset: 0
        back_color: '#00000000'
        back_padding: 0
        back_radius: 0

    - default: studio                                       # Studio - Bottom Right
      template_variables:
        horizontal_align: right
        vertical_align: bottom
        back_align: right
        horizontal_offset: 0
        vertical_offset: 0
        back_color: '#00000000'
        back_height: 80
        back_padding: 0
        studio_font_size: 50